name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
        nextcloud-versions: ['stable21', 'stable22', 'stable23']
        include:
          - php-versions: '7.4'
            nextcloud-versions: 'master'
          # - php-versions: '8.0'
          #   nextcloud-versions: 'stable21'
          # - php-versions: '8.0'
          #   nextcloud-versions: 'master'
    name: php${{ matrix.php-versions }} on ${{ matrix.nextcloud-versions }} unit tests
    env:
      CI: true
      XDEBUG_MODE: coverage
    steps:
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ctype, curl, dom, gd, gmp, iconv, intl, json, mbstring, openssl, pdo_sqlite, posix, sqlite, xml, zip
        coverage: xdebug

    - name: Checkout server
      uses: actions/checkout@master
      with:
        repository: nextcloud/server
        ref: ${{ matrix.nextcloud-versions }}
        path: nextcloud
        submodules: recursive

    - name: Checkout the app
      uses: actions/checkout@master
      with:
        path: nextcloud/apps/tasks

    - name: Install Nextcloud
      run: php -f nextcloud/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''

    - name: Enable app
      run: php -f nextcloud/occ app:enable tasks

    - name: Fix php-parser on stable20 incompatibility with phpunit 9.3+
      if: ${{ matrix.nextcloud-versions == 'stable20' }}
      working-directory: nextcloud/3rdparty
      run: composer require nikic/php-parser:4.10

    - name: Downgrade phpunit for php7.2
      if: ${{ matrix.php-versions == '7.2' }}
      working-directory: nextcloud/apps/tasks
      run: composer update christophwurst/nextcloud_testing -W

    - name: Install dependencies
      working-directory: nextcloud/apps/tasks
      run: composer install

    - name: Run unit tests
      working-directory: nextcloud/apps/tasks
      run: composer run test:unit

    - name: Run integration tests
      working-directory: nextcloud/apps/tasks
      run: composer run test:integration

    - name: Upload coverage to Codecov
      if: ${{ matrix.nextcloud-versions == 'master' }}
      uses: codecov/codecov-action@v3
      with:
        file: nextcloud/apps/tasks/clover.unit.xml
        flags: php
        fail_ci_if_error: true
